### PR TITLE
Alt text for generated markdown badges

### PR DESCRIPTION
**Pull request by KreerC**
All badges should come with a pre-defined alt text for markdown files as it is important for accessibility.

### CODE REVIEW

**Comment by marvinschopf** [comment]
Hi! Thank you so much for your contribution. I'd like to note that this repository (to my knowledge) is no longer maintained because Niklas and I decided to build on serverless and created a new repository  ([GitHub-Badge-Generator-Serverless](https://github.com/Jugendhackt/GitHub-Badge-Generator-Serverless)). Would you mind starting the PR again in that repo?

**Comment by KreerC** [comment]
My change is to the code of the builder interface, which currently recommends markdown notation without a screenreader-accessible alt text - **not the generator itself!** I only found the builder code to be present in this repository, and this is also where builder.jhbadge.de links.

**Comment by marvinschopf** [comment]
The Builder also got a new repo, which can be found [**here**](https://github.com/Jugendhackt/GitHub-Badges-Builder). I have already contacted Niklas to mark this repo as archived. Would you mind doing your PR [there](https://github.com/Jugendhackt/GitHub-Badges-Builder) again?

**Comment by niklasschroetler** [comment]
Very important remark @nkreer. Will definitely add when setting up again!

**Pull request merged**
